### ISSUE TITLE
Support sdk_r18

### ISSUE THREAD

**Issue by guetux** [jvoegele/gradle-android-plugin#60]
First of all, great plugin, thanks so much for your much appreciated work! Unfortunatley i get a NPE when i when try to use the plugin on my local machine using sdk_r18. Probably the SDK changed somewhat of it's internal architecture? However, it uses the AndroidSetup_r14 class to setup the project. Here's the stacktrace:

```
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'some_lame_app'.
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
    ... shortened ...
    at org.gradle.launcher.GradleMain.main(GradleMain.java:24)
Caused by: : java.lang.NullPointerException
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
    at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:71)
    at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:86)
    at org.gradle.api.internal.project.DefaultAntBuilder.super$3$invokeMethod(DefaultAntBuilder.groovy)
    at org.gradle.api.internal.project.DefaultAntBuilder.invokeMethod(DefaultAntBuilder.groovy:37)
    at com.jvoegele.gradle.plugins.android.AndroidSetup_r14.setup(AndroidSetup_r14.groovy:49)
    at com.jvoegele.gradle.plugins.android.AndroidSetup$setup.call(Unknown Source)
    at com.jvoegele.gradle.plugins.android.AndroidPlugin.androidSetup(AndroidPlugin.groovy:89)
    at com.jvoegele.gradle.plugins.android.AndroidPlugin.apply(AndroidPlugin.groovy:77)
    at com.jvoegele.gradle.plugins.android.AndroidPlugin.apply(AndroidPlugin.groovy)
    at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.providePlugin(DefaultProjectsPluginContainer.java:107)
    ... shortened ...
```

Does somebody else have the same issue? Or is this my fault somehow?

**Comment by ealden** [comment]
I believe this is fixed already in master, but hasn't been released yet.  We are in the process of releasing 1.2.0 which should be compatible with the latest Android SDK and Gradle 1.0-rc-3.

Let me prepare a SNAPSHOT build later tonight and I'll upload it to Maven Central so you can try it.

**Comment by guetux** [comment]
By the way, i can confirm that using the master branch 1.1.1-SNAPSHOT it works perfectly with r18. So basically this issue  is a copy of #56 :-)
