### ISSUE TITLE
My project fails to build when using the gradle plugin on Windows

### ISSUE THREAD

**Issue by jroyals** [jvoegele/gradle-android-plugin#77]
The plugin contains an error that results in an exception when building a project that uses it on Windows...

```
22:09:34.716 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:09:34.722 [ERROR] [org.gradle.BuildExceptionReporter]
22:09:34.726 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
22:09:34.730 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':androidProcessResources'.
22:09:34.734 [ERROR] [org.gradle.BuildExceptionReporter] > Unexpected internal error near index 1
22:09:34.739 [ERROR] [org.gradle.BuildExceptionReporter]   \
22:09:34.744 [ERROR] [org.gradle.BuildExceptionReporter]    ^
22:09:34.751 [ERROR] [org.gradle.BuildExceptionReporter]
22:09:34.756 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
22:09:34.762 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':androidProcessResources'.

....

22:09:35.037 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
22:09:35.042 [ERROR] [org.gradle.BuildExceptionReporter] \
22:09:35.047 [ERROR] [org.gradle.BuildExceptionReporter]  ^
22:09:35.051 [ERROR] [org.gradle.BuildExceptionReporter]        at java_lang_String$replaceAll.call(Unknown Source)
22:09:35.056 [ERROR] [org.gradle.BuildExceptionReporter]        at com.jvoegele.gradle.tasks.android.ProcessAndroidResources.generateBuildConfigFile(ProcessAndroidResources.groovy:98)
22:09:35.061 [ERROR] [org.gradle.BuildExceptionReporter]        at com.jvoegele.gradle.tasks.android.ProcessAndroidResources.process(ProcessAndroidResources.groovy:90)
22:09:35.065 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:216)
...
```

As the stack trace indicates, a problem exists on line 98 in `com.jvoegele.gradle.tasks.android.ProcessAndroidResources`.The problem is that in WIndows, File.separator is a backslash character and it requires escaping in a regex. A fix would be to simply replace all slashes (back or forward) with dots.

Changing line 98 to this worked for me ... `def packageDeclaration = packageDir.replaceAll( /[\/\\]/, '.' )`.

**Comment by jvdvegt** [comment]
It seems the code has changed slightly in 1.2.1, to this: `def packageDeclaration = packageDir.replaceAll( File.separator, '.' )`.
Unfortunately, that is guaranteed to not to work on Windows systems, as File.separator is not a valid regular expression.
It should have been this: 
`def packageDeclaration = packageDir.replaceAll(Matcher.quoteReplacement(File.separator), '.' )`. Anyone care to fix this on trunk?

**Comment by joemccall86** [comment]
I submitted a pull request based on your suggestion, jvdvTechno:
https://github.com/jvoegele/gradle-android-plugin/pull/89
